#!/usr/bin/env bash
# Scaffold a new customer: key pair, directories, group_vars, inventories.
#
#   ./new-customer.sh <slug> "<Display Name>" [control_node_ip]
#
#   ./new-customer.sh clientb "Client B"
#   ./new-customer.sh clientb "Client B" 192.168.1.13
#
# <slug> must be lowercase/dashes — it names the folder, the key, and the
# offboard confirmation token. Idempotent: safe to re-run, never overwrites
# an existing key or all.yml.
set -euo pipefail

usage() { sed -n '2,11p' "$0" | sed 's/^# \?//'; exit 1; }

SLUG="${1:-}"; NAME="${2:-}"; NODE_IP="${3:-}"
[ -z "$SLUG" ] || [ -z "$NAME" ] && usage
[[ "$SLUG" =~ ^[a-z0-9-]+$ ]] || { echo "ERROR: slug must be lowercase letters, digits, dashes."; exit 1; }

cd "$(dirname "$0")"
REPO="$PWD"
# Customer data lives OUTSIDE the clone: this repo is public, and a git pull
# must never touch it. Override with MSP_DATA_ROOT if you keep it elsewhere.
DATA_ROOT="${MSP_DATA_ROOT:-$HOME/customers}"
DATA="${DATA_ROOT}/${SLUG}"
KEY="$HOME/.ssh/${SLUG}_ansible"
# Portable form for the committed all.yml — Ansible expands ~ per user,
# so the file works on any control VM regardless of the login name.
KEY_TILDE="~/.ssh/${SLUG}_ansible"

echo "== 1/4 key pair =="
mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
if [ -f "$KEY" ]; then
  echo "  exists, keeping: $KEY"
else
  ssh-keygen -t ed25519 -N "" -C "ansible-${SLUG}" -f "$KEY" >/dev/null
  echo "  created: $KEY"
fi
PUBKEY="$(cat "${KEY}.pub")"

echo "== 2/4 directories =="
mkdir -p "$DATA/group_vars"

echo "== 3/4 inventories =="
[ -f "$DATA/managed.ini" ] || {
  printf '# Hosts under management. No creds — this VM holds the key.\n[managed]\n' > "$DATA/managed.ini"
  echo "  created: $DATA/managed.ini"
}
[ -f "$DATA/onboarding.ini" ] || {
  cp "$REPO/customers/clientA/onboarding.example.ini" "$DATA/onboarding.ini" 2>/dev/null \
    || printf '[new_hosts]\n' > "$DATA/onboarding.ini"
  echo "  created: $DATA/onboarding.ini  (optional — add-host.sh does not need it)"
}

echo "== 4/4 group_vars =="
if [ -f "$DATA/group_vars/all.yml" ]; then
  echo "  exists, NOT overwriting: $DATA/group_vars/all.yml"
else
  cat > "$DATA/group_vars/all.yml" <<EOF
---
# Generated by new-customer.sh on $(date +%Y-%m-%d)
customer_name: ${NAME}
mgmt_user: svc_ansible

# Public half of this customer's key. Private half: ${KEY_TILDE}
mgmt_authorized_keys:
  - "${PUBKEY}"

# The IP customer hosts SEE when this control VM connects — confirm with:
#   ssh <host> 'echo \$SSH_CLIENT'    (first field)
# A wrong value locks this VM out of every host at once.
control_node_ips:
  - "${NODE_IP:-CHANGE_ME}"

# false = sudo needs a password (supply with --ask-become-pass)
mgmt_sudo_nopasswd: true

# Connection to MANAGED hosts. The key below must match mgmt_authorized_keys.
ansible_user: "{{ mgmt_user }}"
ansible_ssh_private_key_file: "${KEY_TILDE}"

# Per-customer connection specifics, e.g.:
# ansible_ssh_common_args: '-o ProxyJump=svc_ansible@bastion.${SLUG}.example.com'
EOF
  echo "  created: $DATA/group_vars/all.yml"
fi

python3 -c "import yaml,sys; yaml.safe_load(open('$DATA/group_vars/all.yml'))" 2>/dev/null \
  && echo "  YAML valid" || echo "  WARNING: could not validate YAML (python3/pyyaml missing?)"

echo
if [ -z "$NODE_IP" ]; then
  cat <<EOF
⚠  control_node_ips is CHANGE_ME. Set it before onboarding anything:
     ssh <a-customer-host> 'echo \$SSH_CLIENT'      # first field
     \$EDITOR $DATA/group_vars/all.yml
EOF
fi
cat <<EOF

Customer '${SLUG}' ready.

  1. Verify control_node_ips in $DATA/group_vars/all.yml
  2. Add a host:
       ./add-host.sh ${SLUG} <ip> <login-user> <path-to-their-key.pem>
  3. Back up ${DATA} and ${KEY} — they are the only copies.
     Nothing here is committed: this repo is public.

  Offboard token for this customer: ${SLUG}
EOF
